spring:
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    suffix: .ftl               #指定Freemarker模板文件的后缀名
    template-loader-path: classpath:/templates
xxl:
  job:
    admin:
      # xxl 管理带的地址
      addresses: http://192.168.200.130:8888/xxl-job-admin
    executor: #执行器
      # 执行器的名字 （保证和页面配置的APPName一模一样）
      appname: leadnews-hot-article-executor
      # 没有任何含义，但是不同服务器必须不一样
      port: 9993